/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/linux-basic': RouteRecordInfo<
      '/posts/linux-basic',
      '/posts/linux-basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MIT Missing Semester/data-organization': RouteRecordInfo<
      '/posts/MIT Missing Semester/data-organization',
      '/posts/MIT%20Missing%20Semester/data-organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MIT Missing Semester/debug-and-profile': RouteRecordInfo<
      '/posts/MIT Missing Semester/debug-and-profile',
      '/posts/MIT%20Missing%20Semester/debug-and-profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MIT Missing Semester/overview-and-shell': RouteRecordInfo<
      '/posts/MIT Missing Semester/overview-and-shell',
      '/posts/MIT%20Missing%20Semester/overview-and-shell',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MIT Missing Semester/shell-env': RouteRecordInfo<
      '/posts/MIT Missing Semester/shell-env',
      '/posts/MIT%20Missing%20Semester/shell-env',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MIT Missing Semester/shell-tools-and-scripts': RouteRecordInfo<
      '/posts/MIT Missing Semester/shell-tools-and-scripts',
      '/posts/MIT%20Missing%20Semester/shell-tools-and-scripts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MIT Missing Semester/version-control': RouteRecordInfo<
      '/posts/MIT Missing Semester/version-control',
      '/posts/MIT%20Missing%20Semester/version-control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MIT Missing Semester/vim': RouteRecordInfo<
      '/posts/MIT Missing Semester/vim',
      '/posts/MIT%20Missing%20Semester/vim',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/painting-practice': RouteRecordInfo<
      '/posts/painting-practice',
      '/posts/painting-practice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Poem-of-the-Unfettered-Void': RouteRecordInfo<
      '/posts/Poem-of-the-Unfettered-Void',
      '/posts/Poem-of-the-Unfettered-Void',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/The-Reverie-Forsaken-Land': RouteRecordInfo<
      '/posts/The-Reverie-Forsaken-Land',
      '/posts/The-Reverie-Forsaken-Land',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tittle-tattle/as-for-sex': RouteRecordInfo<
      '/posts/tittle-tattle/as-for-sex',
      '/posts/tittle-tattle/as-for-sex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tittle-tattle/college': RouteRecordInfo<
      '/posts/tittle-tattle/college',
      '/posts/tittle-tattle/college',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tittle-tattle/life-education': RouteRecordInfo<
      '/posts/tittle-tattle/life-education',
      '/posts/tittle-tattle/life-education',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/windows-basic': RouteRecordInfo<
      '/posts/windows-basic',
      '/posts/windows-basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-lolimeow@1.0.6_vue@3.5.33_typescript@6.0.3_/node_modules/valaxy-theme-lolimeow/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.6_@babel+parser_eb7f216b944ae2ddd78ba147f9073a3d/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-lolimeow@1.0.6_vue@3.5.33_typescript@6.0.3_/node_modules/valaxy-theme-lolimeow/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'pages/posts/linux-basic.md': {
      routes:
        | '/posts/linux-basic'
      views:
        | never
    }
    'pages/posts/MIT Missing Semester/data-organization.md': {
      routes:
        | '/posts/MIT Missing Semester/data-organization'
      views:
        | never
    }
    'pages/posts/MIT Missing Semester/debug-and-profile.md': {
      routes:
        | '/posts/MIT Missing Semester/debug-and-profile'
      views:
        | never
    }
    'pages/posts/MIT Missing Semester/overview-and-shell.md': {
      routes:
        | '/posts/MIT Missing Semester/overview-and-shell'
      views:
        | never
    }
    'pages/posts/MIT Missing Semester/shell-env.md': {
      routes:
        | '/posts/MIT Missing Semester/shell-env'
      views:
        | never
    }
    'pages/posts/MIT Missing Semester/shell-tools-and-scripts.md': {
      routes:
        | '/posts/MIT Missing Semester/shell-tools-and-scripts'
      views:
        | never
    }
    'pages/posts/MIT Missing Semester/version-control.md': {
      routes:
        | '/posts/MIT Missing Semester/version-control'
      views:
        | never
    }
    'pages/posts/MIT Missing Semester/vim.md': {
      routes:
        | '/posts/MIT Missing Semester/vim'
      views:
        | never
    }
    'pages/posts/painting-practice.md': {
      routes:
        | '/posts/painting-practice'
      views:
        | never
    }
    'pages/posts/Poem-of-the-Unfettered-Void.md': {
      routes:
        | '/posts/Poem-of-the-Unfettered-Void'
      views:
        | never
    }
    'pages/posts/The-Reverie-Forsaken-Land.md': {
      routes:
        | '/posts/The-Reverie-Forsaken-Land'
      views:
        | never
    }
    'pages/posts/tittle-tattle/as-for-sex.md': {
      routes:
        | '/posts/tittle-tattle/as-for-sex'
      views:
        | never
    }
    'pages/posts/tittle-tattle/college.md': {
      routes:
        | '/posts/tittle-tattle/college'
      views:
        | never
    }
    'pages/posts/tittle-tattle/life-education.md': {
      routes:
        | '/posts/tittle-tattle/life-education'
      views:
        | never
    }
    'pages/posts/windows-basic.md': {
      routes:
        | '/posts/windows-basic'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
